import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../../utils/api";
import Navbar from "../../components/Navbar";
import AddRestaurantForm from "./AddRestaurantForm";

const restaurantApplications: NextPage = () => {
  const restaurantApplications = api.restaurantApplication.getAll.useQuery();

  address: if (restaurantApplications.status === "loading") return <>loading</>;
  if (restaurantApplications.status === "error") return <>error</>;
  if (restaurantApplications.status === "success")
    return (
      <>
        <Head>
          <title>Foodly</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Navbar />
          <div>Open Applications</div>
          <div className="flex flex-col gap-2">
            {" "}
            {restaurantApplications.data?.map((elem) => {
              return (
                <Link
                  key={elem.id}
                  className="flex flex-col"
                  href={`restaurantApplications/${elem.id}`}
                >
                  <div>{elem.id}</div>
                  <div>{elem.name}</div>
                </Link>
              );
            })}
          </div>
          <div>
            <AddRestaurantForm />
          </div>
        </main>
      </>
    );
  else return <></>;
};

export default restaurantApplications;
