import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../../../utils/api";
import { useRouter } from "next/router";
import Navbar from "../../../components/Navbar";

const SingleRestaurant: NextPage = () => {
  const router = useRouter();
  const { applicationId } = router.query;

  const restaurantApplication = api.restaurantApplication.getById.useQuery({
    id: String(applicationId),
  });

  if (restaurantApplication.status === "loading") return <>loading</>;
  if (restaurantApplication.status === "error") return <>error</>;
  if (restaurantApplication.status === "success")
    return (
      <>
        <Head>
          <title>Foodly</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Navbar />
          <div>
            <div className="flex flex-col">
              <div>{`Application #${restaurantApplication?.data?.id}`} </div>
              <div>
                Application created---
                {restaurantApplication.data?.created_at.toLocaleDateString()}
              </div>
              <span className="text-lg">
                {`name: ${restaurantApplication.data?.name}`}
              </span>
              <div>{`address: ${restaurantApplication.data?.address}`}</div>
              <div>{`city: ${restaurantApplication.data?.cityName}`}</div>
              <div>{`state: ${restaurantApplication.data?.stateName}`}</div>
              <div>{`zip-code: ${restaurantApplication.data?.zipCode}`}</div>
              <div>{`cuisineType: ${restaurantApplication.data?.cuisineType}`}</div>
              <div>{`email: ${restaurantApplication.data?.email}`}</div>
              <div>{`hours: ${restaurantApplication.data?.hoursInterval}`}</div>
              <div>{`phone: ${restaurantApplication.data?.phone}`}</div>
              <div>{`website: ${restaurantApplication.data?.website}`}</div>
            </div>
          </div>
        </main>
      </>
    );
  else return <></>;
};

export default SingleRestaurant;
