"use client";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../../utils/api";
import { useEffect, useMemo, useState } from "react";
import { Restaurant } from "@prisma/client";
import { useRouter } from "next/router";
import Layout from "../../components/Layout";
import RestaurantCard from "../../components/RestaurantCard";
import Link from "next/link";
import SearchForm from "../../components/SearchForm";
import RestaurantSearchForm from "../../components/RestaurantsSearchForm";

const Restaurant: NextPage = () => {
  const router = useRouter();
  const params = router.query;
  const [city, setCity] = useState<string>("");
  const [state, setState] = useState<string>("");

  useEffect(() => {
    if (params.city) {
      localStorage.setItem("city", String(params.city));
    }
    if (params.state) {
      localStorage.setItem("state", String(params.state));
    }
  }, [params]);
  useEffect(() => {
    if (localStorage.getItem("city") && localStorage.getItem("city") !== null) {
      const searchedCity = localStorage.getItem("city");
      setCity(searchedCity || "");
    }
    if (localStorage.getItem("state") && localStorage.getItem("state")) {
      const searchedState = localStorage.getItem("state");
      setState(searchedState || "");
    }
  }, []);

  const apiRestaurants = api.restaurant.getByCityAndState.useQuery({
    city,
    state,
  });
  const dbRestaurants = api.restaurant.getByCityAndStateFromDB.useQuery({
    city,
    state,
  });
  const handleSearchByCity = (e: React.SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault();
    const form = e.currentTarget;
    const formElements = form.elements as typeof form.elements & {
      city: { value: string };
      state: { value: string };
    };
    setCity(formElements.city.value);
    setState(formElements.state.value);
    router.push(
      `/restaurant?city=${formElements.city.value}&state=${formElements.state.value}`
    );
    window.localStorage.setItem("city", city);
    window.localStorage.setItem("state", state);
  };
  useMemo(() => {
    if (apiRestaurants.status === "success") {
      window.localStorage.setItem(
        "restaurants",
        JSON.stringify(apiRestaurants.data)
      );
    }
  }, [apiRestaurants.data, apiRestaurants.status]);

  return (
    <>
      <Head>
        <title>Foodly</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {" "}
        <section className="py-12">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex flex-col gap-2">
              <div className="mx-auto my-8 max-w-4xl px-4">
                <RestaurantSearchForm
                  city={city}
                  state={state}
                  setCity={setCity}
                  setState={setState}
                />
                <form
                  className="flex content-center items-center gap-4  text-center  sm:flex-col md:flex-row lg:flex-row"
                  onSubmit={handleSearchByCity}
                >
                  <div>
                    <Link href="/restaurant/create">
                      <div className="rounded-full bg-blue-500 py-2 px-4 font-bold text-white hover:bg-blue-700">
                        add Restaurant
                      </div>
                    </Link>
                  </div>
                </form>
              </div>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
                {dbRestaurants.data?.map((elem) => {
                  return <RestaurantCard restaurant={elem} key={elem.id} />;
                })}
                {apiRestaurants.data?.map((elem: Restaurant) => {
                  return <RestaurantCard restaurant={elem} key={elem.id} />;
                })}
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default Restaurant;
