import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../../utils/api";

const Restaurant: NextPage = () => {
    const restaurant = api.restaurant.getAll.useQuery();
    console.log(restaurant)
    if (restaurant.status === "loading") return <>loading</>
    if (restaurant.status === 'error') return <>error</>
    if (restaurant.status === 'success')
        return (
            <>
                <Head>
                    <title>Foodly</title>
                    <meta name="description" content="Generated by create-t3-app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">

                    <div className="flex flex-col items-center gap-2">
                        <p className="text-2xl text-white">
                            {restaurant.data.map((elem) => {
                                return <Link href={`/restaurant/${elem.id}`}>{elem.name}</Link>
                            })}
                        </p>
                    </div>
                </main>
            </>
        );
    else return <></>
};


export default Restaurant;

