import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../../utils/api";
import Navbar from "../../components/Navbar";
import { useMemo, useState } from "react";

const Restaurant: NextPage = () => {
  const [city, setCity] = useState<null | string>(null);
  const [state, setState] = useState<null | string>(null);
  const savedRestaurants = api.restaurant.getAll.useQuery();
  const restaurants = api.restaurant.getByCityAndState.useQuery({
    city,
    state,
  });

  const handleSearchByCity = (e: React.SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault();
    const form = e.currentTarget;
    const formElements = form.elements as typeof form.elements & {
      city: { value: string };
      state: { value: string };
    };
    setCity(formElements.city.value);
    setState(formElements.state.value);
  };
  useMemo(() => {
    if (restaurants.status === "success") {
      window.localStorage.setItem(
        "restaurants",
        JSON.stringify(restaurants.data)
      );
    }
  }, [restaurants.data]);
  address: if (restaurants.status === "loading") return <>loading</>;
  if (restaurants.status === "error") return <>error</>;
  if (restaurants.status === "success")
    return (
      <>
        <Head>
          <title>Foodly</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Navbar />
          <div className="flex flex-col gap-2">
            {" "}
            <form onSubmit={handleSearchByCity}>
              <label>City:</label>
              <input
                type="text"
                name="city"
                className="bg-gray-200"
                placeholder="city"
              ></input>
              <label>State:</label>
              <input
                type="text"
                name="state"
                className="bg-gray-200"
                placeholder="state"
              ></input>
              <button type="submit" className="bg-gray-200">
                search now
              </button>
            </form>
            {restaurants.data?.map((elem) => {
              return (
                <Link
                  key={elem.id}
                  className="flex flex-col"
                  href={`restaurant/search/${elem.id}`}
                >
                  <div>{elem.id}</div>
                  <div>{elem.name}</div>
                </Link>
              );
            })}
            {savedRestaurants.data?.map((elem) => {
              return (
                <Link
                  key={elem.id}
                  className="flex flex-col"
                  href={`restaurant/${elem.id}`}
                >
                  <div>{elem.id}</div>
                  <div>{elem.name}</div>
                </Link>
              );
            })}
          </div>
        </main>
      </>
    );
  else return <></>;
};

export default Restaurant;
