import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../../../utils/api";
import { useRouter } from "next/router";
import Favorite from "./Favorite";
import Layout from "../../../components/Layout";

const User: NextPage = () => {
  const router = useRouter();
  const { userId } = router.query;

  const user = api.user.getUserPageData.useQuery({ id: String(userId) });

  const favorites = api.favorite.getByUserId.useQuery({ id: String(userId) });

  return (
    <>
      <Head>
        <title>Foodly</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-col">
          <div>user page</div>
          <div>
            <div>
              <span className="font-bold">username:</span>

              {user.data?.username}
            </div>
          </div>
          <div className="flex flex-col">
            <div className="text-lg font-bold">Favorites</div>
            {favorites.data?.map((elem) => {
              return (
                <Favorite key={elem.id} restaurantId={elem.restaurant_id} />
              );
            })}
          </div>
        </div>
      </Layout>
    </>
  );
};

export default User;
