import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../../../utils/api";
import { URLSearchParams } from "url";
import { useRouter } from "next/router";
import { FormEventHandler } from "react";
import Navbar from "../../../components/Navbar";

const User: NextPage = () => {
    const router = useRouter()
    const { userId } = router.query

    // const restaurant = api.user.getUser.useQuery({ id: String(userId) });


    return (
        <>
            <Head>
                <title>Foodly</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <Navbar />
                <div >
                    <p >
                        user page

                    </p>


                </div>
            </main>
        </>
    );
};


export default User;

