import { type NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/Layout";
import { api } from "../../utils/api";
import ReportedPhotoCard from "./ReportedPhotoCard";

const ReportedItems: NextPage = () => {
  const reportedPhotos = api.reportedPhoto.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Foodley</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-col">
          <h2 className="mb-8 text-3xl font-bold">reported photos</h2>
          {reportedPhotos.data?.map((reportedPhoto) => (
            <ReportedPhotoCard
              key={reportedPhoto.id}
              reportedPhoto={reportedPhoto}
            />
          ))}
        </div>
      </Layout>
    </>
  );
};

export default ReportedItems;
