import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import Navbar from "../components/Navbar";
import { api } from "../utils/api";


const Profile: NextPage = () => {
    const user = api.user.getUser.useQuery();
    const updateUsername = api.user.updateUsername.useMutation()


    const handleSubmit = (e: React.SyntheticEvent<HTMLFormElement>) => {
        e.preventDefault()
        const form = e.currentTarget
        const formElements = form.elements as typeof form.elements & {
            username: { value: string }
        }
        updateUsername.mutate({ username: formElements.username.value }, {
            onSuccess() {
                user.refetch()
            }
        })

    }
    return (
        <>
            <Head>
                <title>Foodly</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <Navbar />
                <div >
                    <p >
                        profile
                    </p>
                    {user.data?.email}
                    {user.data?.username ? <>
                        {user.data.username}
                    </>
                        : <></>}
                    <form onSubmit={handleSubmit}>
                        <input name="username"></input><button type="submit">make userName</button></form>
                </div>
            </main>
        </>
    );

};


export default Profile;


