import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { URLSearchParams } from "url";
import { useRouter } from "next/router";
import { FormEventHandler } from "react";
import { api } from "../../../../utils/api";
import Navbar from "../../../../components/Navbar";

interface IRestaurantData {
  cityName: string;
  cuisineType: string;
  email: string;
  hoursInterval: string;
  id: number;
  latitude: string;
  longitude: string;
  phone: string;
  restaurantName: string;
  stateName: string;
  website: string;
  zipCode: string;
}

const SingleRestaurant: NextPage = () => {
  const router = useRouter();
  const { restaurantId } = router.query;
  const restaurantJSON: string | null =
    window.localStorage.getItem("restaurants");

  const singleResraurantData: IRestaurantData | null = JSON.parse(
    restaurantJSON ? restaurantJSON : ""
  ).find((elem: IRestaurantData) => {
    return elem.id === Number(restaurantId);
  });

  //   const createComment = api.comment.createComment.useMutation();
  //   const createFavorite = api.favorite.createFavorite.useMutation();
  //   const deleteFavorite = api.favorite.delete.useMutation();
  //   const isFavorited = api.favorite.isRestaurantFavorited.useQuery({
  //     restaurantId: String(restaurantId),
  //   });

  //   const handleFavorite = (e: React.SyntheticEvent<HTMLButtonElement>) => {
  //     e.preventDefault();
  //     createFavorite.mutate(
  //       { placement: 1, restaurantId: String(restaurantId) },
  //       {
  //         async onSuccess() {
  //           await isFavorited.refetch();
  //         },
  //       }
  //     );
  //   };
  //   const handleUnfavorite = (e: React.SyntheticEvent<HTMLButtonElement>) => {
  //     e.preventDefault();
  //     deleteFavorite.mutate(
  //       { restaurantId: String(restaurantId) },
  //       {
  //         async onSuccess() {
  //           await isFavorited.refetch();
  //         },
  //       }
  //     );
  //   };

  return (
    <>
      <Head>
        <title>Foodly</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div>
          <div className="flex flex-col">
            <span className="text-lg">single restaurant page</span>
            <div>{singleResraurantData?.restaurantName}</div>
          </div>
        </div>
      </main>
    </>
  );
};

export default SingleRestaurant;
