import { type NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/Layout";
import { api } from "../../utils/api";
import CommentCard from "./CommentCard";

const User: NextPage = () => {
  const comments = api.comment.getRecent.useQuery();

  return (
    <>
      <Head>
        <title>Foodley</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="py-12">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <h2 className="mb-8 text-3xl font-bold">Latest Reviews</h2>
            <div className="flex flex-wrap gap-4">
              {comments.data?.map((elem) => {
                return (
                  <div>
                    <CommentCard comment={elem} key={elem.id} />
                  </div>
                );
              })}
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default User;
