import { type NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/Layout";
import { api } from "../../utils/api";
import CommentCard from "./CommentCard";

const User: NextPage = () => {
  const comments = api.comment.getRecent.useQuery();

  return (
    <>
      <Head>
        <title>Foodly</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="bg-gray-100 py-12">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <h2 className="mb-8 text-3xl font-bold">Latest Reviews</h2>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
              {comments.data?.map((elem) => {
                return <CommentCard comment={elem} key={elem.id} />;
              })}
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default User;
