import { type NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/Layout";
import { api } from "../../utils/api";
import UserList from "./UserList";

const Admin: NextPage = () => {
  const users = api.user.getAll.useQuery();
  const updateRole = api.user.updateRole.useMutation();
  const handleRoleChange = (e: React.SyntheticEvent<HTMLButtonElement>) => {
    e.preventDefault();

    if (user.data?.role !== "ADMIN") {
      updateRole.mutate(
        {
          role: "ADMIN",
        },
        {
          onSuccess() {
            user.refetch();
          },
        }
      );
    } else {
      updateRole.mutate(
        {
          role: "USER",
        },
        {
          onSuccess() {
            user.refetch();
          },
        }
      );
    }
  };
  return (
    <>
      <Head>
        <title>Foodly</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-col">
          <h2 className="mb-8 text-3xl font-bold">Admin Dashboard</h2>
          <UserList users={users.data || []} />
        </div>
      </Layout>
    </>
  );
};

export default Admin;
